#!/usr/bin/env python3
"""Write supplementary tables for the endpoint-layer manuscript revision."""
from __future__ import annotations

from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
OUT = Path("/root/source_native_benchmark_revision_2026-07-04/formal_rsc_digital_discovery_revision/supplementary_endpoint_tables.tex")
EVAL = ROOT / "outputs" / "repaired_model_evaluation_v2"
AUDIT = ROOT / "outputs" / "evidence_strengthening_v1" / "complete_case_audit"
TRAINING = ROOT / "outputs" / "evidence_strengthening_v1" / "model_training_overlap"


def esc(value: object) -> str:
    return str(value).replace("_", "\\_").replace("%", "\\%")


def longtable(caption: str, label: str, columns: str, rows: list[str]) -> str:
    return "\n".join([
        f"\\begin{{longtable}}{{{columns}}}",
        f"\\caption{{{caption}}}\\label{{{label}}}\\\\",
        "\\toprule",
        "\\endfirsthead",
        "\\toprule",
        "\\endhead",
        "\\bottomrule",
        "\\endfoot",
        *rows,
        "\\end{longtable}",
        "",
    ])


def main() -> None:
    chunks: list[str] = ["% Generated by scripts/build_endpoint_layer_supplementary.py.\n"]
    support = pd.read_csv(EVAL / "all_view_common_support_exclusion_audit.csv")
    chunks.append(longtable(
        "Route from the exact three-source cohort to the primary M1 common-support cohort.",
        "tab:support-audit", "p{0.33\\linewidth}r r p{0.37\\linewidth}",
        [f"{esc(r.stage)} & {int(r.n):,} & {('--' if pd.isna(r.excluded_vs_d5) else int(r.excluded_vs_d5))} & {esc(r.rule)} \\\\" for r in support.itertuples()],
    ))

    raw = pd.read_csv(EVAL / "score_construct_validity_audit.csv")
    chunks.append(longtable(
        "AUROC audit of archived raw energies and predicted-hull rankings on M1. AUROC is evaluated against MP-native endpoints.",
        "tab:raw-validity", "l r r r",
        [f"{esc(r.model_name)} & {r.raw_energy_rank_auroc_mp_native:.3f} & {r.reverse_raw_energy_rank_auroc_mp_native:.3f} & {r.predicted_hull_rank_auroc_mp_native:.3f} \\\\" for r in raw.itertuples()],
    ))
    chunks.append("\\noindent Table~\\ref{tab:raw-validity}: columns are model, archived raw-energy AUROC, reversed raw-energy AUROC and predicted-hull AUROC.\n\n")

    metrics = pd.read_csv(EVAL / "metrics_fixed_support.csv")
    chunks.append(longtable(
        "Fixed-support metrics for predicted-hull rankings (M1, $n=31{,}872$). Binary metrics use the fixed MP-native positive-count prediction set ($n_+=13{,}205$).",
        "tab:m1-metrics", "l l r r r r r",
        [f"{esc(r.model_name)} & {esc(r.label_view)} & {r.f1_fixed_threshold:.3f} & {r.auroc:.3f} & {r.auprc:.3f} & {r.ap_lift:.3f} & {r.positive_rate:.3f} \\\\" for r in metrics.itertuples()],
    ))
    chunks.append("\\noindent Table~\\ref{tab:m1-metrics}: columns are model, endpoint, F1, AUROC, AUPRC, AP lift and endpoint positive rate.\n\n")

    bands = pd.read_csv(EVAL / "band_and_model_spread_fixed_support.csv")
    ratios = pd.read_csv(EVAL / "endpoint_sensitivity_to_model_spread_ratio_bootstrap.csv")
    headline_metrics = {"f1_fixed_threshold", "auroc", "auprc", "stable_yield_at_1000"}
    band_rows = bands[
        bands.scope.isin(["source_native_sensitivity", "hull_construction_sensitivity"])
        & bands.model_name.notna()
        & bands.metric.isin(headline_metrics)
    ]
    merged = band_rows.merge(ratios, on=["scope", "model_name", "metric"], how="left")
    chunks.append(longtable(
        "Source-native and hull-construction endpoint bands with paired bootstrap ratios to the median four-model spread.",
        "tab:endpoint-bands", "l l l r r r r",
        [f"{esc(r.scope.replace('_', ' '))} & {esc(r.model_name)} & {esc(r.metric)} & {r.spread:.3f} & {r.ratio_median:.3f} & {r.ratio_ci_low_95:.3f} & {r.ratio_ci_high_95:.3f} \\\\" for r in merged.itertuples()],
    ))

    audit = bands[(bands.scope.eq("audit_policy_consequence")) & bands.model_name.notna() & bands.metric.isin(headline_metrics)]
    chunks.append(longtable(
        "Audit-policy consequence: absolute MP-native-to-audit endpoint differences on M1.",
        "tab:audit-policy", "l l r",
        [f"{esc(r.model_name)} & {esc(r.metric)} & {r.spread:.3f} \\\\" for r in audit.itertuples()],
    ))

    consensus = pd.read_csv(EVAL / "metrics_consensus_selection_policy.csv")
    chunks.append(longtable(
        "Consensus selection-policy metrics (24,614 retained agreement rows).",
        "tab:consensus-selection", "l r r r r r",
        [f"{esc(r.model_name)} & {int(r.n):,} & {r.f1_fixed_threshold:.3f} & {r.auroc:.3f} & {r.auprc:.3f} & {r.ap_lift:.3f} \\\\" for r in consensus.itertuples()],
    ))
    chunks.append("\\noindent Table~\\ref{tab:consensus-selection}: columns are model, rows, F1, AUROC, AUPRC and AP lift.\n\n")

    deltas = pd.read_csv(EVAL / "paired_label_view_differences_cluster_bootstrap.csv")
    deltas = deltas[(deltas.metric.eq("stable_yield_at_1000")) & (deltas.view_a.eq("mp_native")) & deltas.view_b.isin(["alex_pbe_native", "common_pool", "audit_view"])]
    chunks.append(longtable(
        "Paired chemical-system bootstrap differences in stable yield at $K=1000$ (1,000 replicates; seed 20260714). Difference is MP-native minus the comparison endpoint.",
        "tab:paired-yield", "l l r r r r",
        [f"{esc(r.model_name)} & {esc(r.view_b)} & {r.point_delta_a_minus_b:.3f} & {r.bootstrap_ci_low_95:.3f} & {r.bootstrap_ci_high_95:.3f} & {r.probability_delta_gt_zero:.3f} \\\\" for r in deltas.itertuples()],
    ))
    chunks.append("\\noindent Table~\\ref{tab:paired-yield}: columns are model, comparison endpoint, point difference, 95\\% interval lower and upper bounds, and the fraction of replicates with $\\Delta>0$.\n\n")

    winners = pd.read_csv(EVAL / "model_winner_probabilities_cluster_bootstrap.csv")
    chunks.append(longtable(
        "Model winner frequencies from paired chemical-system bootstrap replicates on M1.",
        "tab:winner-probabilities", "l l l r",
        [f"{esc(r.label_view)} & {esc(r.metric)} & {esc(r.model_name)} & {r.winner_probability:.3f} \\\\" for r in winners.itertuples()],
    ))

    numeric = pd.read_csv(AUDIT / "d5_to_m1_numeric_comparison.csv")
    chunks.append(longtable(
        "M1 retained-versus-excluded comparison for numeric features. SMD denotes standardized mean difference.",
        "tab:selection-numeric", "p{0.35\\linewidth}r r r r r",
        [f"{esc(r.feature_label)} & {r.retained_mean:.3f} & {r.excluded_mean:.3f} & {r.retained_median:.3f} & {r.excluded_median:.3f} & {r.standardized_mean_difference:.3f} \\\\" for r in numeric.itertuples()],
    ))

    conflict = pd.read_csv(AUDIT / "d5_to_m1_label_and_conflict_comparison.csv")
    chunks.append(longtable(
        "M1 retained-versus-excluded endpoint and source-switch rates.",
        "tab:selection-conflict", "l r r r r",
        [f"{esc(r.feature)} & {int(r.retained_n):,} & {int(r.excluded_n):,} & {r.retained_rate:.3f} & {r.excluded_rate:.3f} \\\\" for r in conflict.itertuples()],
    ))
    chunks.append("\\noindent Table~\\ref{tab:selection-conflict}: columns are feature, retained rows, excluded rows, retained rate and excluded rate.\n")

    training = pd.read_csv(TRAINING / "model_training_overlap_audit.csv")
    training_status = {
        "ALIGNN-FF": "JARVIS-linked identifiers are recorded separately; a direct release membership table is unavailable.",
        "CHGNet": "Every M1 row carries a Materials Project identifier.",
        "M3GNet": "Release-specific membership identifiers are required for row-level assignment.",
        "MACE-MP": "Every M1 row carries a Materials Project identifier.",
    }
    chunks.append(longtable(
        "Model checkpoint and training-corpus provenance for the M1 comparison.",
        "tab:training-overlap", "@{}p{0.12\\linewidth}p{0.24\\linewidth}p{0.22\\linewidth}p{0.34\\linewidth}@{}",
        [f"{esc(r.model)} & {esc(r.release_identifier)} & {esc(r.training_corpus)} & {training_status[r.model]} \\\\" for r in training.itertuples()],
    ))
    OUT.write_text("\n".join(chunks), encoding="utf-8")


if __name__ == "__main__":
    main()
