#!/usr/bin/env python3
"""Build a manuscript-visible source-field card from frozen source records."""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CARDS = ROOT / "outputs" / "phase1_v2" / "benchmark_cards"
OUT = ROOT / "outputs" / "referee_revision_v3" / "source_input_card"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    cards = {key: json.loads((CARDS / file).read_text()) for key, file in {
        "mp": "source_mp.json", "mattergen": "source_alexmp20.json", "alexandria": "source_alex_pbe.json",
    }.items()}
    rows = [
        {
            "source": "Materials Project", "snapshot_or_query": "MP Summary API queried 2026-05-20",
            "native_hull_input": "materials.summary.energy_above_hull", "analysis_hull_field": cards["mp"]["hull_stability_field"],
            "native_label_field": cards["mp"]["label_field_name"],
            "formation_energy_input": "materials.summary.formation_energy_per_atom", "formation_energy_available": True,
            "unit": cards["mp"]["unit"], "official_threshold": cards["mp"]["stable_threshold"],
        },
        {
            "source": "MatterGen alex-mp-20", "snapshot_or_query": "MatterGen data-release alex_mp_20.zip; train.csv + val.csv",
            "native_hull_input": "energy_above_hull", "analysis_hull_field": cards["mattergen"]["hull_stability_field"],
            "native_label_field": cards["mattergen"]["label_field_name"],
            "formation_energy_input": "not present in released score table", "formation_energy_available": False,
            "unit": cards["mattergen"]["unit"], "official_threshold": cards["mattergen"]["stable_threshold"],
        },
        {
            "source": "official Alexandria-PBE", "snapshot_or_query": "PBE 3D snapshot 2025.07.02; retrieved 2026-07-05",
            "native_hull_input": "entries[].data.e_above_hull", "analysis_hull_field": cards["alexandria"]["hull_stability_field"],
            "native_label_field": cards["alexandria"]["label_field_name"],
            "formation_energy_input": "entries[].data.e_form", "formation_energy_available": True,
            "unit": cards["alexandria"]["unit"], "official_threshold": cards["alexandria"]["stable_threshold"],
        },
    ]
    card = pd.DataFrame(rows)
    card.to_csv(OUT / "source_input_card.csv", index=False)
    card.to_json(OUT / "source_input_card.json", orient="records", indent=2)

    tex = r'''% Generated by build_source_input_card_v3.py; do not edit.
\begin{table*}[!t]
\centering
\caption{Source fields used to construct the physical endpoint layer. The listed native fields are continuous energy-above-hull coordinates. Binary labels are regenerated at the declared threshold and audited against the released native labels. Formation-energy inputs enter only the MP and Alexandria-PBE matched-pool coordinates.}
\label{tab:source-input-card}
\tiny
\setlength{\tabcolsep}{2pt}
\begin{tabular}{@{}p{0.14\textwidth}p{0.24\textwidth}p{0.25\textwidth}p{0.21\textwidth}p{0.12\textwidth}@{}}
\toprule
Source & Snapshot / query & Native continuous field & Formation-energy field & Unit; threshold \\
\midrule
Materials Project & MP Summary API, 2026-05-20 & \texttt{energy\_above\_hull} & \texttt{formation\_energy\_per\_atom} & eV atom$^{-1}$; $\leq10^{-8}$ \\
MatterGen alex-mp-20 & MatterGen release archive; training and validation tables & \texttt{energy\_above\_hull} & unavailable in released score table & eV atom$^{-1}$; $\leq10^{-8}$ \\
official Alexandria-PBE & PBE 3D 2025.07.02; retrieved 2026-07-05 & \texttt{entries[].data.e\_above\_hull} & \texttt{entries[].data.e\_form} & eV atom$^{-1}$; $\leq10^{-8}$ \\
\bottomrule
\end{tabular}
\end{table*}
'''
    (OUT / "table_source_input_card.tex").write_text(tex, encoding="utf-8")
    print(card.to_string(index=False))


if __name__ == "__main__":
    main()
